# Generated by Django 4.2.7 on 2023-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
